"""empty message

Revision ID: f43afd54535c
Revises: 
Create Date: 2021-06-25 03:53:46.280096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43afd54535c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('cidian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eng', sa.String(length=100), nullable=False),
    sa.Column('sp', sa.String(length=100), nullable=False),
    sa.Column('img_url', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cidian')
    op.drop_table('user')
    # ### end Alembic commands ###
